"""Prepare, run and collect a relax-then-IR calculation.

The three steps are separate on purpose:

:func:`prepare`
    Validates the structure and the settings, and writes a self-contained
    directory (see :mod:`carbonforge.vibspec.core.record`). Needs no DFT code,
    so it runs on Windows.
:func:`run`
    Relaxes, re-checks, and computes the IR spectrum by finite differences
    (:class:`ase.vibrations.Infrared`). Needs GPAW; run it where GPAW is, with
    the generated ``run.py``::

        mpiexec -n 4 gpaw python run.py

    It is restartable: a converged relaxation is not repeated, and ASE's
    displacement cache means an interrupted IR run resumes where it stopped,
    which matters under a cluster's wall-time limit.
:func:`collect`
    Reads the result back as a
    :class:`~carbonforge.results.spectra.VibrationalSpectrum`.

Physics enforced along the way: nothing runs if :meth:`CalcSpec.validate`
reports an error; the vibrations do not start unless the relaxation reached
``fmax`` and :func:`check_ready_for_vibrations` passes on the *relaxed*
structure (a pyrrolic ring that did not close stops here); and the six
rigid-body modes of the molecule (five if linear) are identified and kept
out of the spectrum, with a warning if they are far from zero -- the sign of
an unconverged relaxation or a coarse grid.
"""

from __future__ import annotations

import traceback
from pathlib import Path
from typing import Optional

import numpy as np
from ase import Atoms
from ase.io import read, write
from ase.optimize import BFGS
from ase.parallel import world

from ...results.spectra import VibrationalMode, VibrationalSpectrum
from .calcspec import CalcSpec
from .checks import check_ready_for_vibrations, suggest_spin
from .engines import CalculatorFactory, make_gpaw_calculator
from .record import RECORD_FILE, CalcRecord, code_versions

#: Rigid-body modes further than this from zero mean the structure is not
#: at a clean minimum, or the grid breaks translational invariance. Not
#: tighter, because two harmless effects each give tens of cm^-1: the
#: residual force allowed by fmax = 0.01 eV/Å acting on a hydrogen, and the
#: finite-difference error of a 0.01 Å step (it grows linearly with delta).
RIGID_MODE_TOLERANCE_CM1: float = 100.0

#: Internal modes more imaginary than this invalidate the spectrum.
IMAGINARY_TOLERANCE_CM1: float = 20.0

IR_INTENSITY_UNIT = "(D/Å)²/amu"

_RUN_SCRIPT = '''"""Generated by carbonforge vibspec.

Run where GPAW is installed:
    mpiexec -n 4 gpaw python run.py     (in parallel)
    python run.py                        (serial)
It can be re-run after an interruption: finished steps are not repeated.
"""
from pathlib import Path

from carbonforge.vibspec.core.workflow import run

run(Path(__file__).resolve().parent)
'''


class VibspecError(RuntimeError):
    """A calculation was refused or stopped for a physical reason."""


def _master() -> bool:
    return world.rank == 0


def _save(record: CalcRecord, directory: Path) -> None:
    if _master():
        record.save(directory)
    world.barrier()


def _report_dict(report) -> dict:
    return {"errors": list(report.errors), "warnings": list(report.warnings),
            "info": dict(report.info)}


def prepare(
    atoms: Atoms,
    spec: CalcSpec,
    directory: Path,
    name: Optional[str] = None,
    force: bool = False,
    overwrite: bool = False,
) -> CalcRecord:
    """Validate and write a calculation directory.

    Parameters
    ----------
    atoms
        Finite structure, e.g. from a vibspec preset. Its ``info`` (the
        provenance of the preset) is kept in ``initial.xyz``.
    spec
        Calculation settings.
    directory
        Where to write. Must not already hold a calculation unless
        ``overwrite``.
    name
        Label for the catalogue; defaults to the directory name.
    force
        Write even when validation reports errors. The errors stay in the
        record, and :func:`run` still refuses them.
    overwrite
        Replace an existing calculation in ``directory``.

    Returns
    -------
    CalcRecord
        The record as saved, with status ``prepared``.

    Raises
    ------
    VibspecError
        If validation fails and ``force`` is not set.
    """
    directory = Path(directory)
    if (directory / RECORD_FILE).exists() and not overwrite:
        raise FileExistsError(
            f"{directory} ya contiene un cálculo. Usa otro directorio u overwrite=True."
        )
    report = spec.validate(atoms)
    if not report.ok and not force:
        raise VibspecError("La preparación no pasa la validación:\n" + report.summary())

    directory.mkdir(parents=True, exist_ok=True)
    record = CalcRecord(
        name=name or directory.name,
        spec=spec.to_dict(),
        formula=atoms.get_chemical_formula(),
        n_atoms=len(atoms),
        preset=atoms.info.get("vibspec_preset"),
        files={"initial": "initial.xyz", "script": "run.py"},
        checks={"prepare": _report_dict(report)},
    )
    record.set_status("prepared", "validación superada" if report.ok else "forzado con errores")
    if _master():
        write(directory / "initial.xyz", atoms)
        (directory / "run.py").write_text(_RUN_SCRIPT, encoding="utf-8")
    _save(record, directory)
    return record


def _max_force(atoms: Atoms) -> float:
    return float(np.linalg.norm(atoms.get_forces(), axis=1).max())


def _is_linear(atoms: Atoms) -> bool:
    if len(atoms) < 3:
        return True
    inertia = np.sort(atoms.get_moments_of_inertia())
    return inertia[0] < 1e-3 * max(inertia[-1], 1e-12)


def _signed(frequencies: np.ndarray) -> np.ndarray:
    """ASE's complex frequencies as real numbers, imaginary ones negative."""
    real, imag = np.abs(frequencies.real), np.abs(frequencies.imag)
    return np.where(imag > real, -imag, real)


def _relax(atoms: Atoms, spec: CalcSpec, directory: Path, record: CalcRecord) -> Atoms:
    record.set_status("relaxing", f"BFGS hasta fmax={spec.fmax} eV/Å")
    _save(record, directory)
    optimizer = BFGS(
        atoms,
        trajectory=str(directory / "relax.traj"),
        logfile=str(directory / "relax.log"),
        append_trajectory=True,
    )
    converged = bool(optimizer.run(fmax=spec.fmax, steps=spec.max_steps))
    fmax = _max_force(atoms)
    record.relax = {
        "converged": converged,
        "steps": int(optimizer.get_number_of_steps()),
        "fmax": fmax,
        "energy_eV": float(atoms.get_potential_energy()),
    }
    if not converged:
        raise VibspecError(
            f"La relajación no convergió en {spec.max_steps} pasos (fuerza residual "
            f"{fmax:.4f} eV/Å). Sube max_steps o revisa la estructura; no se calculan "
            "vibraciones sobre una geometría sin relajar."
        )
    if _master():
        write(directory / "relaxed.xyz", atoms)
    record.files["relaxed"] = "relaxed.xyz"
    record.set_status("relaxed", f"fuerza residual {fmax:.4f} eV/Å")
    _save(record, directory)
    return atoms


def _vibrations(atoms: Atoms, spec: CalcSpec, directory: Path, record: CalcRecord) -> None:
    from ase.vibrations import Infrared

    record.set_status("vibrations", f"{6 * len(atoms) if spec.nfree == 2 else 12 * len(atoms)} "
                                    "desplazamientos")
    _save(record, directory)
    ir = Infrared(atoms, name=str(directory / "ir"), delta=spec.delta, nfree=spec.nfree)
    ir.run()
    ir.read(method=spec.ir_method)
    frequencies = _signed(np.asarray(ir.get_frequencies(method=spec.ir_method)))
    intensities = np.asarray(ir.intensities, dtype=float)
    modes = np.array([ir.get_mode(i) for i in range(len(frequencies))])

    n_rigid = 5 if _is_linear(atoms) else 6
    order = np.argsort(np.abs(frequencies))
    rigid = np.sort(order[:n_rigid])
    internal = np.sort(order[n_rigid:])

    warnings: list[str] = []
    rigid_max = float(np.abs(frequencies[rigid]).max()) if len(rigid) else 0.0
    if rigid_max > RIGID_MODE_TOLERANCE_CM1:
        warnings.append(
            f"Los modos de sólido rígido llegan a {rigid_max:.0f} cm⁻¹ (deberían estar "
            "cerca de 0): relajación insuficiente o rejilla demasiado gruesa (efecto "
            "huevera). Los modos bajos del espectro no son fiables."
        )
    imaginary = [float(f) for f in frequencies[internal] if f < -IMAGINARY_TOLERANCE_CM1]
    if imaginary:
        warnings.append(
            f"{len(imaginary)} modo(s) interno(s) imaginario(s), hasta {min(imaginary):.0f} "
            "cm⁻¹: la estructura no está en un mínimo. Relaja más antes de asignar bandas."
        )

    if _master():
        np.savez(
            directory / "modes.npz",
            frequencies_cm1=frequencies, intensities=intensities, modes=modes,
            rigid=rigid, internal=internal,
        )
    record.files["modes"] = "modes.npz"
    record.results = {
        "frequencies_cm1": frequencies[internal].tolist(),
        "ir_intensity": intensities[internal].tolist(),
        "mode_indices": internal.tolist(),
        "intensity_unit": IR_INTENSITY_UNIT,
        "n_rigid": n_rigid,
        "rigid_max_cm1": rigid_max,
        "imaginary_cm1": imaginary,
        "scale_factor": spec.scale_factor,
        "ir_method": spec.ir_method,
        "warnings": warnings,
    }


def run(
    directory: Path,
    calculator_factory: Optional[CalculatorFactory] = None,
) -> CalcRecord:
    """Relax and compute the IR spectrum of a prepared calculation.

    Parameters
    ----------
    directory
        A directory written by :func:`prepare`.
    calculator_factory
        ``factory(spec, txt, spinpol) -> Calculator``. Defaults to GPAW.

    Returns
    -------
    CalcRecord
        With status ``done``. Already-finished calculations are returned
        untouched.

    Raises
    ------
    VibspecError
        When a physical check stops the calculation. The record is saved
        with status ``error`` and the reason, so a batch job both fails
        visibly and leaves the explanation on disk.
    """
    directory = Path(directory)
    record = CalcRecord.load(directory)
    if record.status == "done":
        return record
    factory = calculator_factory or make_gpaw_calculator
    spec = CalcSpec.from_dict(record.spec)
    # The numbers come from the machine that runs, not the one that prepared.
    record.versions = {**code_versions(), "prepared_with": record.versions.get("carbonforge")}

    try:
        report = spec.validate(read(directory / record.files["initial"]))
        if not report.ok:
            raise VibspecError("La especificación no pasa la validación:\n" + report.summary())

        relaxed = bool(record.relax.get("converged")) and "relaxed" in record.files
        initial = read(directory / record.files["initial"])
        info = dict(initial.info)
        if relaxed:
            atoms = read(directory / record.files["relaxed"])
        elif (directory / "relax.traj").exists():
            # An interrupted or unconverged relaxation continues from its last step.
            atoms = initial
            atoms.set_positions(read(directory / "relax.traj", index=-1).get_positions())
        else:
            atoms = initial

        spinpol = spec.resolved_spinpol(atoms)
        if spinpol:
            atoms.set_initial_magnetic_moments(
                suggest_spin(atoms, charge=spec.charge).magmoms
            )
        atoms.calc = factory(spec, directory / "gpaw.txt", spinpol)

        if not relaxed:
            atoms = _relax(atoms, spec, directory, record)
        atoms.info = info

        gate = check_ready_for_vibrations(
            atoms, relaxed_fmax=record.relax.get("fmax"), spinpol=spinpol, charge=spec.charge,
        )
        record.checks["vibrations"] = _report_dict(gate)
        if not gate.ok:
            raise VibspecError("La estructura relajada no pasa la comprobación previa a las "
                               "vibraciones:\n" + gate.summary())

        _vibrations(atoms, spec, directory, record)
        record.error = None
        record.set_status("done", f"{len(record.results['frequencies_cm1'])} modos internos")
        _save(record, directory)
        return record
    except Exception as exc:
        record.error = "".join(traceback.format_exception(exc))
        record.set_status("error", str(exc).splitlines()[0] if str(exc) else type(exc).__name__)
        _save(record, directory)
        raise


def collect(directory: Path) -> VibrationalSpectrum:
    """The IR spectrum of a finished calculation, rigid-body modes excluded.

    Frequencies are the raw computed ones; the scale factor stored with the
    calculation is applied at analysis time, never in place.
    """
    record = CalcRecord.load(Path(directory))
    if record.status != "done":
        raise VibspecError(f"{directory}: el cálculo está en estado '{record.status}', no 'done'.")
    results = record.results
    modes = [
        VibrationalMode(index=int(i), frequency_cm1=float(f), ir_activity=float(a))
        for i, f, a in zip(results["mode_indices"], results["frequencies_cm1"],
                           results["ir_intensity"], strict=True)
    ]
    return VibrationalSpectrum(modes=modes, has_ir=True, expected_acoustic=0)
