"""Vibrational spectroscopy setups: phonons, infrared and Raman.

Quantum ESPRESSO computes all three with density-functional perturbation
theory (DFPT) in ``ph.x``, followed by ``dynmat.x`` to turn the dynamical
matrix into frequencies and intensities. The workflow is:

    pw.x  (scf)  →  ph.x  (dynamical matrix, ε∞, Raman tensors)  →  dynmat.x

Three prerequisites bite people repeatedly, so they are encoded here and
checked by :mod:`carbonforge.validation.calculations` before anything is
written:

1. **IR intensities need Born effective charges**, i.e. ``epsil=.true.``,
   which QE can only compute for a system with a band gap. Armchair CNTs and
   pristine graphene are metallic or semimetallic, so the run will stop.
2. **Raman needs norm-conserving pseudopotentials.** QE's DFPT Raman
   implementation does not support PAW or ultrasoft, which are exactly the
   defaults most people (and this package) otherwise use.
3. **Raman also needs** ``epsil=.true.``, so it inherits the gap requirement.

Frequencies alone (``trans=.true.`` with no ``epsil``) have none of these
restrictions and work fine for metals with PAW.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, Sequence

SpectroscopyMode = Literal["phonon", "ir", "raman", "ir+raman"]


@dataclass
class SpectroscopySpec:
    """Settings for a vibrational-spectroscopy run.

    Attributes
    ----------
    mode
        ``"phonon"`` (frequencies only), ``"ir"``, ``"raman"`` or
        ``"ir+raman"``.
    qpoint
        Phonon wavevector in crystal coordinates. Spectroscopy compares
        against optical experiments, which probe q ≈ 0, so this defaults to
        Γ. A non-Γ point disables IR/Raman, which are only defined at Γ.
    tr2_ph
        DFPT self-consistency threshold. 1e-14 is the usual production value.
    asr
        Acoustic sum rule applied by ``dynmat.x``: ``"crystal"``,
        ``"simple"``, ``"no"``, or the axis-projected variants. Enforcing it
        pushes the three acoustic modes to zero; without it they come out at
        tens of cm⁻¹ and pollute the low-frequency spectrum.
    laser_wavelength_nm
        Laser line assumed when reporting Raman intensities (``dynmat.x``
        input). 532 nm is the common green laser.
    temperature_k
        Temperature used for the Bose occupation factor in Raman intensities.
    ldisp
        Compute a dispersion over a q-grid instead of a single q. Mutually
        exclusive with IR/Raman intensities.
    nq
        q-grid used when ``ldisp`` is true.
    """

    mode: SpectroscopyMode = "phonon"
    qpoint: tuple[float, float, float] = (0.0, 0.0, 0.0)
    tr2_ph: float = 1.0e-14
    asr: str = "crystal"
    laser_wavelength_nm: float = 532.0
    temperature_k: float = 300.0
    ldisp: bool = False
    nq: tuple[int, int, int] = (1, 1, 1)

    @property
    def needs_epsil(self) -> bool:
        """True when the dielectric response (and thus a gap) is required."""
        return self.mode in ("ir", "raman", "ir+raman")

    @property
    def needs_raman(self) -> bool:
        """True when Raman tensors (and thus NC pseudopotentials) are required."""
        return self.mode in ("raman", "ir+raman")

    @property
    def is_gamma(self) -> bool:
        """True when the phonon wavevector is Γ."""
        return all(abs(component) < 1e-8 for component in self.qpoint)


def raman_setup(**overrides) -> SpectroscopySpec:
    """Build a Γ-point Raman + IR setup.

    Raman implies the dielectric response, so IR intensities come for free;
    the mode is therefore ``"ir+raman"`` rather than Raman alone.
    """
    params = {"mode": "ir+raman", "qpoint": (0.0, 0.0, 0.0)}
    params.update(overrides)
    return SpectroscopySpec(**params)


def infrared_setup(**overrides) -> SpectroscopySpec:
    """Build a Γ-point infrared setup (Born charges, no Raman tensors)."""
    params = {"mode": "ir", "qpoint": (0.0, 0.0, 0.0)}
    params.update(overrides)
    return SpectroscopySpec(**params)


def phonon_setup(**overrides) -> SpectroscopySpec:
    """Build a frequencies-only setup.

    This is the safe option: it works for metals and with any
    pseudopotential family, at the cost of giving no intensities.
    """
    params = {"mode": "phonon"}
    params.update(overrides)
    return SpectroscopySpec(**params)


def format_ph_input(
    spec: SpectroscopySpec,
    prefix: str = "pwscf",
    outdir: str = "./out",
    title: str = "Phonons generated by carbonforge",
) -> str:
    """Render a ``ph.x`` input file.

    Parameters
    ----------
    spec
        The spectroscopy settings.
    prefix, outdir
        Must match the preceding ``pw.x`` scf run, or ``ph.x`` will not find
        the charge density.
    title
        Free-text first line.
    """
    lines = [title, "&INPUTPH"]
    lines.append(f"    prefix = '{prefix}'")
    lines.append(f"    outdir = '{outdir}'")
    lines.append("    fildyn = 'matdyn'")
    lines.append(f"    tr2_ph = {spec.tr2_ph:.3e}")
    lines.append("    trans = .true.")

    if spec.needs_epsil:
        lines.append("    epsil = .true.    ! ε∞ y cargas de Born (IR)")
    if spec.needs_raman:
        lines.append("    lraman = .true.   ! requiere pseudos norm-conserving")

    if spec.ldisp:
        lines.append("    ldisp = .true.")
        lines.append(f"    nq1 = {spec.nq[0]}")
        lines.append(f"    nq2 = {spec.nq[1]}")
        lines.append(f"    nq3 = {spec.nq[2]}")
    lines.append("/")

    if not spec.ldisp:
        q = spec.qpoint
        lines.append(f"{q[0]:.8f} {q[1]:.8f} {q[2]:.8f}")
    return "\n".join(lines) + "\n"


def format_dynmat_input(
    spec: SpectroscopySpec,
    fildyn: str = "matdyn",
) -> str:
    """Render a ``dynmat.x`` input, which turns the dynamical matrix into
    frequencies and IR / Raman intensities.

    The acoustic sum rule matters here: without it the three translational
    modes come out at finite frequency and contaminate the low-wavenumber
    end of the spectrum.
    """
    lines = ["&INPUT"]
    lines.append(f"    fildyn = '{fildyn}'")
    lines.append(f"    asr = '{spec.asr}'")
    lines.append("    filout = 'dynmat.out'")
    lines.append("    fileig = 'dynmat.eig'")
    if spec.needs_epsil:
        # Only meaningful once ph.x has produced the dielectric data.
        lines.append(f"    q(1) = {spec.qpoint[0]:.8f}")
        lines.append(f"    q(2) = {spec.qpoint[1]:.8f}")
        lines.append(f"    q(3) = {spec.qpoint[2]:.8f}")
    if spec.needs_raman:
        lines.append(f"    lperm = .true.")
        lines.append(f"    temperature = {spec.temperature_k:.2f}")
        # dynmat.x takes the laser line in nm.
        lines.append(f"    lambda = {spec.laser_wavelength_nm:.2f}")
    lines.append("/")
    return "\n".join(lines) + "\n"


def format_runner_script(
    spec: SpectroscopySpec,
    pw_input: str = "pw.in",
    ph_input: str = "ph.in",
    dynmat_input: str = "dynmat.in",
    ncores: int = 4,
) -> str:
    """Render a small shell script chaining pw.x → ph.x → dynmat.x.

    The three codes must run in order and share ``prefix``/``outdir``; a
    script removes one common source of mistakes.
    """
    steps = [
        "#!/usr/bin/env bash",
        "# Generated by carbonforge. Run from this directory.",
        "set -euo pipefail",
        "",
        f'NCORES="${{NCORES:-{ncores}}}"',
        'MPI="${MPI:-mpirun -np $NCORES}"',
        "",
        "echo '[1/3] SCF (pw.x)'",
        f'$MPI pw.x -in {pw_input} > pw.out',
        "",
        "echo '[2/3] Phonons (ph.x) — this is the slow step'",
        f'$MPI ph.x -in {ph_input} > ph.out',
        "",
        "echo '[3/3] Frequencies and intensities (dynmat.x)'",
        f"dynmat.x -in {dynmat_input} > dynmat.out",
        "",
        "echo 'Done. Frequencies and intensities are in dynmat.out'",
    ]
    if spec.needs_raman:
        steps.insert(
            3,
            "# Reminder: Raman (lraman) requires norm-conserving "
            "pseudopotentials.\n",
        )
    return "\n".join(steps) + "\n"
