"""Δ-learning (tbkit.delta): forces are the derivative of the energy, and a correction
that is exactly linear in SOAP is recovered by the fit."""

import numpy as np
import pytest

pytest.importorskip("dscribe")

from ase.build import molecule  # noqa: E402

from tbkit.delta import DeltaModel, fit_delta  # noqa: E402


def _random_model(seed=0):
    model = DeltaModel(("C", "H", "O"), r_cut=4.0, n_max=3, l_max=2)
    rng = np.random.default_rng(seed)
    nf = model.n_features()
    model.scale = np.ones(nf)
    model.weights = {z: rng.normal(scale=1e-3, size=nf) for z in model.species}
    model.bias = {"C": -1.0, "H": -0.3, "O": -2.0}
    return model


def test_delta_forces_are_minus_the_energy_gradient():
    model = _random_model()
    atoms = molecule("CH3OH")
    atoms.rattle(0.05, seed=1)
    _, forces = model.energy_forces(atoms)
    h = 1e-4
    for a, c in ((0, 0), (2, 1), (5, 2)):
        plus, minus = atoms.copy(), atoms.copy()
        plus.positions[a, c] += h
        minus.positions[a, c] -= h
        numeric = -(model.energy_forces(plus)[0] - model.energy_forces(minus)[0]) / (2 * h)
        assert forces[a, c] == pytest.approx(numeric, abs=1e-6)


def test_fit_recovers_an_exactly_linear_correction():
    truth = _random_model(3)
    rows = []
    for name in ("CH3OH", "H2CO", "CH3CHO", "HCOOH", "CH4", "H2O", "C2H6", "CH3COOH"):
        for seed in range(3):
            atoms = molecule(name)
            atoms.rattle(0.08, seed=seed)
            e, f = truth.energy_forces(atoms)
            rows.append({"atoms": atoms, "dE": e, "dF": f})
    fitted = fit_delta(rows, ("C", "H", "O"), ridge=1e-10, n_max=3, l_max=2)
    # The data are generated by a model of the fitted form: least squares reproduces
    # them (an unseen molecule need not match: with 405 weights and these data the
    # solution is not unique, which is also why the real fits do not generalise).
    for row in rows:
        _, f = fitted.energy_forces(row["atoms"], row["soap"])
        assert np.allclose(f, row["dF"], atol=1e-4 * np.abs(row["dF"]).max())
    assert fitted.novelty(rows[0]["atoms"]).max() < 1e-6       # training atoms are known
