"""Convergence sweeps for plane-wave cutoff and k-point density.

The defaults this package ships (60 Ry / 480 Ry, automatic k-mesh) are
reasonable starting points, not converged values — and a band gap or a phonon
frequency quoted from an unconverged calculation is simply wrong, however
carefully the rest was done. This module generates the sweep that settles it,
and reads the results back.

The workflow is:

1. :func:`cutoff_sweep` or :func:`kpoint_sweep` writes one input per value,
   plus a shell script that runs them in sequence.
2. You run the script.
3. :func:`read_total_energies` collects the final energies and
   :func:`convergence_table` reports where the change per step falls below
   your tolerance.

Energies are compared **per atom**, so the tolerance means the same thing
across system sizes. The usual target is 1 meV/atom for total-energy
differences; properties like phonon frequencies typically need a higher
cutoff than the energy alone, so converge on the property you actually care
about when it matters.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

import numpy as np
from ase import Atoms

from ..exports.qe import QESettings, write_qe_input

#: 1 Rydberg in electronvolts, for reporting QE energies in eV.
RY_TO_EV = 13.605693122994


@dataclass
class ConvergencePoint:
    """One point of a convergence sweep."""

    label: str
    value: float
    energy_ev: Optional[float] = None
    energy_per_atom_ev: Optional[float] = None


def _write_runner(outdir: Path, names: Sequence[str], title: str) -> Path:
    """Write a shell script running every input in sequence."""
    lines = [
        "#!/usr/bin/env bash",
        f"# {title} — generated by carbonforge.",
        "set -euo pipefail",
        'NCORES="${NCORES:-4}"',
        'MPI="${MPI:-mpirun -np $NCORES}"',
        "",
    ]
    for index, name in enumerate(names, start=1):
        stem = name.removesuffix(".in")
        lines.append(f"echo '[{index}/{len(names)}] {stem}'")
        lines.append(f"$MPI pw.x -in {name} > {stem}.out")
    lines += [
        "",
        "echo 'Listo. Analiza los resultados con:'",
        "echo '  carbonforge converge-report .'",
    ]
    script = outdir / "run_sweep.sh"
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    return script


def cutoff_sweep(
    atoms: Atoms,
    outdir: str | Path,
    cutoffs: Sequence[float] = (40, 50, 60, 70, 80, 90, 100),
    dual: float = 8.0,
    settings: Optional[QESettings] = None,
    force: bool = False,
) -> dict[str, Path]:
    """Write one scf input per plane-wave cutoff.

    Parameters
    ----------
    atoms
        Structure to converge.
    outdir
        Destination directory.
    cutoffs
        ``ecutwfc`` values in Ry.
    dual
        Ratio ``ecutrho / ecutwfc``. 8 is right for norm-conserving
        pseudopotentials; PAW and ultrasoft need 8-12, so raise it if your
        density is under-converged at fixed ``ecutwfc``.
    settings
        Base settings; ``ecutwfc`` and ``ecutrho`` are overridden per point.
    force
        Bypass structural validation.

    Returns
    -------
    dict
        Maps each input's stem to its path, plus ``"script"``.
    """
    if not cutoffs:
        raise ValueError("Se necesita al menos un valor de cutoff.")
    if dual < 4:
        raise ValueError("dual < 4 no tiene sentido físico (ecutrho >= 4*ecutwfc).")

    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    base = settings or QESettings()

    written: dict[str, Path] = {}
    names: list[str] = []
    for cutoff in cutoffs:
        stem = f"ecut_{cutoff:g}"
        point_settings = QESettings(
            **{
                **base.__dict__,
                "calculation": "scf",
                "ecutwfc": float(cutoff),
                "ecutrho": float(cutoff) * dual,
            }
        )
        written[stem] = write_qe_input(
            atoms, outdir, settings=point_settings,
            filename=f"{stem}.in", force=force,
        )
        names.append(f"{stem}.in")

    written["script"] = _write_runner(outdir, names, "Barrido de cutoff")
    return written


def kpoint_sweep(
    atoms: Atoms,
    outdir: str | Path,
    densities: Sequence[float] = (0.40, 0.30, 0.25, 0.20, 0.15, 0.10),
    settings: Optional[QESettings] = None,
    force: bool = False,
) -> dict[str, Path]:
    """Write one scf input per k-point density.

    Parameters
    ----------
    densities
        ``kpoint_density`` values in Å⁻¹. Smaller means a denser mesh, so the
        default sequence goes from coarse to fine.

    Returns
    -------
    dict
        Maps each input's stem to its path, plus ``"script"``.
    """
    if not densities:
        raise ValueError("Se necesita al menos una densidad.")

    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    base = settings or QESettings()

    written: dict[str, Path] = {}
    names: list[str] = []
    for density in densities:
        stem = f"kdens_{density:g}".replace(".", "p")
        point_settings = QESettings(
            **{**base.__dict__, "calculation": "scf",
               "kpoint_density": float(density)}
        )
        written[stem] = write_qe_input(
            atoms, outdir, settings=point_settings,
            filename=f"{stem}.in", force=force,
        )
        names.append(f"{stem}.in")

    written["script"] = _write_runner(outdir, names, "Barrido de puntos k")
    return written


# QE prints the converged energy as "!    total energy = -123.456 Ry".
_ENERGY = re.compile(r"^!\s+total energy\s*=\s*(-?\d+\.\d+)\s*Ry", re.MULTILINE)
_NAT = re.compile(r"number of atoms/cell\s*=\s*(\d+)")


def read_total_energy(path: str | Path) -> tuple[float, Optional[int]]:
    """Extract the final total energy (eV) and atom count from a pw.x output.

    Returns
    -------
    (energy_ev, n_atoms)
        ``n_atoms`` is ``None`` if the header could not be read.

    Raises
    ------
    ValueError
        If no converged total energy is present, which normally means the run
        did not finish.
    """
    text = Path(path).read_text(errors="replace")
    matches = _ENERGY.findall(text)
    if not matches:
        raise ValueError(
            f"{path}: no hay una energía total convergida ('!  total energy'). "
            "El cálculo probablemente no terminó."
        )
    energy_ry = float(matches[-1])
    nat_match = _NAT.search(text)
    n_atoms = int(nat_match.group(1)) if nat_match else None
    return energy_ry * RY_TO_EV, n_atoms


def read_total_energies(
    outdir: str | Path,
    pattern: str = "*.out",
) -> list[ConvergencePoint]:
    """Collect energies from every pw.x output in ``outdir``.

    The sweep parameter is recovered from the filename stem
    (``ecut_60.out`` → 60, ``kdens_0p20.out`` → 0.20). Files that cannot be
    parsed are skipped rather than aborting the whole report, so one crashed
    run does not hide the others.

    Returns
    -------
    list[ConvergencePoint]
        Sorted by the sweep parameter.
    """
    outdir = Path(outdir)
    points: list[ConvergencePoint] = []
    for path in sorted(outdir.glob(pattern)):
        stem = path.stem
        if "_" not in stem:
            continue
        raw = stem.split("_", 1)[1].replace("p", ".")
        try:
            value = float(raw)
        except ValueError:
            continue
        try:
            energy, n_atoms = read_total_energy(path)
        except ValueError:
            continue
        points.append(
            ConvergencePoint(
                label=stem,
                value=value,
                energy_ev=energy,
                energy_per_atom_ev=energy / n_atoms if n_atoms else None,
            )
        )
    points.sort(key=lambda p: p.value)
    return points


def convergence_table(
    points: Sequence[ConvergencePoint],
    tolerance_mev_per_atom: float = 1.0,
    parameter_name: str = "parámetro",
) -> str:
    """Format a convergence report and identify the converged value.

    A point counts as converged when its energy differs from the **next**
    one by less than ``tolerance_mev_per_atom``. Comparing against the next
    point rather than the largest value is deliberate: it answers "can I stop
    here?", which is the actual question.
    """
    if not points:
        return "No se encontraron resultados. ¿Se ejecutó el barrido?"

    usable = [p for p in points if p.energy_per_atom_ev is not None]
    if len(usable) < 2:
        return (
            f"Solo hay {len(usable)} punto(s) con energía por átomo; "
            "se necesitan al menos 2 para juzgar la convergencia."
        )

    lines = [
        f"{'valor':>10}  {'E/átomo (eV)':>16}  {'ΔE vs siguiente':>18}",
        "-" * 50,
    ]
    converged_at: Optional[float] = None
    for index, point in enumerate(usable):
        energy = point.energy_per_atom_ev
        if index < len(usable) - 1:
            delta = abs(usable[index + 1].energy_per_atom_ev - energy) * 1000.0
            marker = " ✓" if delta < tolerance_mev_per_atom else ""
            if delta < tolerance_mev_per_atom and converged_at is None:
                converged_at = point.value
            lines.append(
                f"{point.value:>10g}  {energy:>16.6f}  {delta:>15.3f} meV{marker}"
            )
        else:
            lines.append(f"{point.value:>10g}  {energy:>16.6f}  {'—':>18}")

    lines.append("")
    if converged_at is not None:
        lines.append(
            f"Convergido en {parameter_name} = {converged_at:g} "
            f"(ΔE < {tolerance_mev_per_atom} meV/átomo respecto al siguiente punto)."
        )
    else:
        lines.append(
            f"NO converge dentro de {tolerance_mev_per_atom} meV/átomo en el "
            "rango probado. Extiende el barrido."
        )
    return "\n".join(lines)


def plot_convergence(
    points: Sequence[ConvergencePoint],
    parameter_name: str = "Cutoff (Ry)",
    tolerance_mev_per_atom: float = 1.0,
):
    """Return a matplotlib ``Figure`` of energy per atom against the parameter.

    Energies are plotted relative to the last (best) point, which is the
    quantity that actually matters for deciding where to stop.
    """
    import matplotlib.pyplot as plt  # noqa: WPS433

    usable = [p for p in points if p.energy_per_atom_ev is not None]
    if len(usable) < 2:
        raise ValueError("Se necesitan al menos 2 puntos para graficar.")

    values = np.array([p.value for p in usable])
    energies = np.array([p.energy_per_atom_ev for p in usable])
    relative = (energies - energies[-1]) * 1000.0  # meV/atom

    fig, ax = plt.subplots(figsize=(6.0, 4.0))
    ax.plot(values, relative, "o-", color="#1f4e9c")
    ax.axhline(tolerance_mev_per_atom, color="#c0392b", linestyle="--",
               linewidth=0.8, label=f"±{tolerance_mev_per_atom} meV/átomo")
    ax.axhline(-tolerance_mev_per_atom, color="#c0392b", linestyle="--",
               linewidth=0.8)
    ax.set_xlabel(parameter_name)
    ax.set_ylabel("E − E$_{final}$ (meV/átomo)")
    ax.set_title("Convergencia")
    ax.legend()
    fig.tight_layout()
    return fig
